name: GitHub Actions

on: 
  issues:
    types: [opened]

jobs:
  builds: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Echo Message
      run: echo "New issue has been opened"
         