name: GitHub Actions

on: 
  push:
    branches:
      - main
  
  issues:
    types:
      - opened

env:
  DAY_OF_THE_WEEK: Monday
  FIRST_NAME: John
  Greeting: Hello

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Greet the user
        run: echo "$Greeting $FIRST_NAME. It's $DAY_OF_THE_WEEK"

  # build: 
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Echo Build
  #     run: sleep 10 && "Build lasted for 10 seconds"
  
  # post-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Echo Post Build
  #     run: echo "Build ended on:" ` date`

  
  
