name: GitHub Actions

on: 
  push:
    branches:
      - main

jobs:
  builds: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: |
        date > generated.txt
        echo generated.txt
         