name: GitHub Actions

on: 
  push:
    branches:
      - main

jobs:
  builds: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Echo GitHub Actions
      run: |
        a=5 \
        b=5 \
        echo "expr $a + $b"
         