name: GitHub Actions

on: 
  push:
    branches:
      - main

jobs:
  pre-build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo pre-build
        run: echo "This is the pre-build"

  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Echo Build
      run: sleep 10 && echo "Build lasted for 10 seconds"
  
  post-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Echo Post Build
      run: echo "Build ended on:" ` date`

  
  
